Update French translation
nearby-sharing/android pull request #137
Opened 2024-02-23 21:45 UTC by MaisClement

Hi,

This is just a little update of the french translation 😄

2024-02-23 23:51 UTC, ShortDevelopment requested changes
Hey, thank you very much for your contribution!

There are some minor things to fix:
- The compiler does not allow unescaped apostrophs `'` in xml
You can replace them with `’` or escape them with `\'`
- "Windows" has been removed from the app name for clarity

2024-02-23 23:51 UTC, ShortDevelopment commented on Nearby Sharing Windows/Resources/values-fr/strings.xml
> +	<string name="app_name">Partage de proximité (Windows)</string>
"Windows" has been removed from the name
```suggestion
	<string name="app_name">Partage de proximité</string>
```

2024-02-23 23:51 UTC, ShortDevelopment commented on Nearby Sharing Windows/Resources/values-fr/strings.xml
> +	<string name="switch_language_summary">Changer la langue de l'appli</string>
```suggestion
	<string name="switch_language_summary">Changer la langue de l’appli</string>
```
or
```suggestion
	<string name="switch_language_summary">Changer la langue de l\'appli</string>
```

2024-02-23 23:51 UTC, ShortDevelopment commented on Nearby Sharing Windows/Resources/values-fr/strings.xml
> +	<string name="preference_cdp_summary">Configuration pour l'envoi et la réception</string>
```suggestion
	<string name="preference_cdp_summary">Configuration pour l’envoi et la réception</string>
```

2024-02-23 23:51 UTC, ShortDevelopment commented on Nearby Sharing Windows/Resources/values-fr/strings.xml
> +	<string name="wait_for_acceptance">Terminé</string>
duplicate of `wait_for_acceptance`

2024-02-24 09:57 UTC, MaisClement commented
Hi,
I'm taking your review into consideration, let me know if there is anything else wrong.

2024-02-24 16:05 UTC, merged

2024-02-24 16:29 UTC, 5T748CowJuy commented
Thank you.. I will need to look up translations moving forward.