Updated Spanish and add Catalan translations
nearby-sharing/android pull request #153
Opened 2024-04-22 10:00 UTC by Sappstal

2024-04-22 10:20 UTC, ShortDevelopment requested changes

2024-04-22 10:20 UTC, ShortDevelopment commented on Nearby Sharing Windows/Resources/values-ca/strings.xml
> +<string name="sending_template">Enviant ... {0}/{1} arxius... {2}%</string>
I changed this template
https://github.com/nearby-sharing/android/blob/6f84dfca6ad0fd0ce84d6d28d52d5a5bcc8cb9cc/src/Resources/values/strings.xml#L97

2024-04-22 10:20 UTC, ShortDevelopment commented on Nearby Sharing Windows/Resources/values-ca/strings.xml
> +<string name="app_name">Ús compartit en proximitat (Nearby Sharing Windows)</string>
I removed "Windows" from the title

2024-04-22 10:20 UTC, ShortDevelopment commented on Nearby Sharing Windows/Resources/values-ca/strings.xml
> +<string name="app_name">Ús compartit en proximitat (Nearby Sharing Windows)</string>
Please only use either the language-specific or english name

2024-04-22 10:20 UTC, ShortDevelopment commented on Nearby Sharing Windows/Assets/ca/MacAddressInfo.html
> +https://github.com/shortdevelopment/nearby-sharing-windows/issues
The repo has moved to `https://github.com/nearby-sharing/android`

2024-04-22 13:58 UTC, Sappstal commented
Hi! Sorry, I had some trouble with the branch and some files' older versions were duplicated. I'll close this PR and fix it.

2024-04-26 20:32 UTC, ShortDevelopment requested changes

2024-04-26 20:32 UTC, ShortDevelopment commented on src/Resources/values-ca/strings.xml
> +<string name="app_name">Ús compartit en proximitat de Windows</string>
```suggestion
<string name="app_name">Ús compartit en proximitat</string>
```

2024-04-26 20:32 UTC, ShortDevelopment commented on src/Resources/values-es/strings.xml
> +	<string name="app_name">Uso compartido en proximidad de Windows</string>
```suggestion
	<string name="app_name">Uso compartido en proximidad</string>
```

2024-04-26 20:39 UTC, ShortDevelopment commented
@Sappstal No problem!
I recommend you delete your fork **AFTER** this is merged and create a fresh fork.
Then you can modify stuff by [creating a new branch](https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project#creating-a-branch-to-work-on) and open a PullRequests for your feature- / patch-branch.
It's also possible to create / edit a file [directly in the GitHub UI](https://docs.github.com/en/repositories/working-with-files/managing-files/creating-new-files)!

This way you wont have merge-conflicts all the time.

2024-04-28 21:10 UTC, ShortDevelopment requested changes
Last thing: Please add this entry to `./values-ca/strings.xml`:
```xml
<string name="assets_prefix">ca</string>
```

2024-04-30 20:12 UTC, ShortDevelopment approved these changes
Sry, everything is fine!
Thank you for your contribution!

2024-04-30 20:25 UTC, merged