add tw strings
nearby-sharing/android pull request #154
Opened 2024-04-22 10:30 UTC by NeKoOuO

2024-04-22 10:32 UTC, ShortDevelopment commented
@NeKoOuO Please add yourself to [`CREDITS.md`](https://github.com/nearby-sharing/android/blob/main/CREDITS.md) by pushing a new commit onto this PR

2024-04-22 10:38 UTC, NeKoOuO commented
done

2024-04-22 10:44 UTC, ShortDevelopment requested changes
@NeKoOuO The tag `tw` stands for the language [Twi](https://en.wikipedia.org/wiki/Twi)
Please get the correct one from the [iana language-subtag-registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry).

2024-04-22 10:44 UTC, ShortDevelopment commented on src/Resources/values-tw/strings.xml
> +	<string name="assets_prefix">zh</string>
Please follow the [Wiki](https://github.com/nearby-sharing/android/wiki/Contributing#add-translation) to add the missing translations and set this `assets_prefix` to the correct language-prefix afterwards

2024-04-22 10:57 UTC, ShortDevelopment requested changes

2024-04-22 10:57 UTC, ShortDevelopment commented on src/Resources/values-tw/strings.xml
> +	<string name="assets_prefix">zh-tw</string>
Based on your description you might want to use `zh-Hant-TW`
> Type: redundant
Tag: zh-Hant-TW
Description: Taiwan Chinese in traditional script
Added: 2005-04-11

2024-04-22 13:14 UTC, NeKoOuO commented
done

2024-04-22 13:42 UTC, ShortDevelopment commented
You should also rename your files to match this new pre- / postfix.

2024-04-26 16:11 UTC, NeKoOuO commented
Done!

2024-04-26 20:27 UTC, ShortDevelopment commented
@NeKoOuO Now you just need to follow the rest of [this Wiki entry](https://github.com/nearby-sharing/android/wiki/Contributing#add-translation) to add the missing translation for the welcome and setup page

2024-05-18 16:21 UTC, NeKoOuO commented
Done !

2024-05-20 19:28 UTC, ShortDevelopment commented
Great, thank you very much!
I'll test this and then merge it afterwards!

2024-09-03 07:12 UTC, ShortDevelopment approved these changes

2024-09-03 07:15 UTC, NeKoOuO commented
> Thank you very much for your contribution!
> I'm sorry this took so long; I've been quite busy over the last view months 🙈

Thanks 😌

2024-09-03 08:25 UTC, merged